# Dockerfile

# 1. Valitse pohja-image
FROM python:3.10-slim

# 2. Aseta työskentelyhakemisto kontin sisällä
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# 3. Kopioi koko hakemisto työhakemistoon
COPY . .

# 4. Määrittele komento, joka ajetaan kun kontti käynnistetään
CMD ["python", "calculator.py"]

CMD ["tail", "-f", "/dev/null"]
