name: Python Calculator Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asentaa pytest, requests ym.
      - name: Build the Docker image
        run: docker build -t calculator-app .
      - name: Run the Docker container
        run: docker run -d --name calculator calculator-app
      - name: Run Robot Framework tests
        run: docker exec calculator robot test.robot
